Homework1
ok-technopolis-2020/Marasanov_Roman pull request #1
Opened 2020-10-13 15:53 UTC by romanmarasanov

2020-10-13 15:59 UTC, romanmarasanov commented
Почему-то гит очень не хочет отображать нужные изменения в этом ПР. Попробуйте пойти сюда: Code->Homework1 (в строке с .idea). Там виден весь html-файл

2020-10-13 16:57 UTC, fromanywhere commented
.idea — это скрытая служебная директория, её по-хорошему вообще в гитигнор кладут. Поэтому неудивительно, что изменения не особо видны.
Давайте перенесем всё просто в index.html в корень.
По коду — всё почти хорошо, только я бы убрал там форму, мы не будем слать данные на сервер _таким_ образом.
Соответственно уйдут `type` у `<button>`.
Кнопка для включения-выключения не прочтется читалкой — нужен aria-label
И всё это, конечно, не таблица, а список

2020-10-13 17:37 UTC, romanmarasanov commented
Поправил. 
Немного смущает, что мы вручную предусматриваем в разметке 3 условных задания, но ведь в итоге готовая штука должна позволять иметь произвольное число задач. Ещё не ясно, как кнопочка вниз около формы ввода нового задания связана с самой формой. Это всё в рамках разметки не реализовывается?

2020-10-13 17:47 UTC, fromanywhere requested changes

2020-10-13 17:47 UTC, fromanywhere commented on Index.html
> +        <button>V</button>
тут aria-label

2020-10-13 17:47 UTC, fromanywhere commented on Index.html
> +        <input type="text" placeholder="What needs to be done?" required>
не очень ясно, зачем тут required

2020-10-13 17:47 UTC, fromanywhere commented on Index.html
> +                <button type="reset" aria-label="delete the task">X</button>
всё еще type (зачем?)

2020-10-13 17:54 UTC, fromanywhere commented
> Немного смущает, что мы вручную предусматриваем в разметке 3 условных задания, но ведь в итоге готовая штука должна позволять иметь произвольное число задач. 

Всё верно.
Подразумевается, что макет предусматривает демонстрацию разных состояний. Ну, то есть по-хорошему конечно у одного из чекбоксов должно быть checked-состояние
Тут можно поспорить, что понятно, зачем два, но зачем все остальные. По идее, незачем — потребность в точном следовании макету будет справедлива для макетов со стилями

> Ещё не ясно, как кнопочка вниз около формы ввода нового задания связана с самой формой. Это всё в рамках разметки не реализовывается?
Вообще предполагается, что у нас тут client-side, поэтому сама сущность формы очень спорна. У нас тут нет ни сабмитов, ничего такого. Можно спорить о том, что форма сделает ввод более легкой — например, если бы там было что-то автозаполнением. У нас всего этого нет, поэтому и `<form>` не предполагается, хотя ошибкой тоже не будет.
Что касается связывания обработки контролов, то предполагается, что да, она выполняется js в этом месте, и сейчас на разметке об этом можно не думать

2020-10-13 20:57 UTC, romanmarasanov commented on Index.html
> +                <button type="reset" aria-label="delete the task">X</button>
Скорее, просто символически в данном случае. Убрал)

2020-10-13 20:58 UTC, romanmarasanov commented on Index.html
> +        <input type="text" placeholder="What needs to be done?" required>
Чтобы форма просила заполнить её при попытке засубмитить пустое поле (хотя мы вроде уже пришли к тому, что форма здесь не маст хэв, так что это я тоже убрал)

2020-10-13 20:59 UTC, romanmarasanov commented on Index.html
> +        <button>V</button>
Добавил

2020-10-14 08:12 UTC, fromanywhere approved these changes

2020-10-18 13:17 UTC, merged